export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const LOAN_LOADING = 'LOAN_LOADING'

export const ADD_LOANS = 'ADD_LOANS'

export const GET_POST = 'GET_POST'

export const ADD_LOAN = 'ADD_LOAN'

export const DELETE_POST = 'DELETE_POST'
